FROM python:3-alpine

# Add your instructions to dockerize the application
# App must run on port 8000

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements
